# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dotnet-utils
  description: "This repo contains utility packages that can be shared between Allegro services."
  title: Allegro.Extensions
  annotations:
    backstage.io/techdocs-ref: dir:.
    allegropay/entity-updated-at: '2024-12-04T08:15'
    github.com/project-slug: allegro/dotnet-utils
  links: []
spec:
  type: library
  owner: aard
  lifecycle: production
  system: application-platform
