name: Build Allegro.Extensions.Financials

on:
  push:
    branches: [ main ]
    paths:
      - 'src/Allegro.Extensions.Financials/**'
      - 'src/*'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/Allegro.Extensions.Financials/**'
      - 'src/*'

jobs:
  ci:
    uses: ./.github/workflows/template.yml
    with:
      projectName: Allegro.Extensions.Financials
      solutionName: Allegro.Extensions.Financials
