name: Publish Allegro.Extensions.Cqrs

on:
  workflow_dispatch: {}
  push:
    tags:
      - 'Allegro.Extensions.Cqrs_*'

jobs:
  publish:
    uses: ./.github/workflows/template.yml
    with:
      projectName: Allegro.Extensions.Cqrs
      solutionName: Allegro.Extensions.Cqrs
      publish: true
      tagName: ${{ github.ref_name }}
    secrets:
      SM_CLIENT_CERT_PASSWORD: ${{ secrets.DIGICERT_SM_CLIENT_CERT_PASSWORD }}
      SM_CLIENT_CERT_FILE_B64: ${{ secrets.DIGICERT_SM_CLIENT_CERT_FILE_B64 }}
      SM_HOST: ${{ secrets.DIGICERT_SM_HOST }}
      SM_API_KEY: ${{ secrets.DIGICERT_SM_API_KEY }}
      SM_CODE_SIGNING_CERT_SHA1_HASH: ${{ secrets.DIGICERT_SM_CODE_SIGNING_CERT_SHA1_HASH }}
      nugetApiKey: ${{ secrets.NUGET_API_KEY }}
