name: Publish Allegro.Extensions.Validators

on:
  push:
    tags:
      - 'Allegro.Extensions.Validators_*'
    branches-ignore:
      - 'feature/*'

jobs:
  publish:
    uses: ./.github/workflows/template.yml
    with:
      projectName: Allegro.Extensions.Validators
      solutionName: Allegro.Extensions.Validators
      publish: true
      tagName: ${{ github.ref_name }}
    secrets:
      nugetCertificate: ${{ secrets.NUGET_PRIVATE_KEY_P12 }}
      nugetCertificatePassword: ${{ secrets.GPG_PRIVATE_KEY_PASSWORD }}
      nugetApiKey: ${{ secrets.NUGET_API_KEY }}
