name: Publish Allegro.Extensions.Dapper

on:
  workflow_dispatch: {}
  push:
    tags:
      - 'Allegro.Extensions.Dapper_*'

jobs:
  publish:
    uses: ./.github/workflows/template.yml
    with:
      projectName: Allegro.Extensions.Dapper
      solutionName: Allegro.Extensions.Dapper
      publish: true
      tagName: ${{ github.ref_name }}
    secrets:
      nugetCertificate: ${{ secrets.NUGET_PRIVATE_KEY_P12 }}
      nugetCertificatePassword: ${{ secrets.GPG_PRIVATE_KEY_PASSWORD }}
      nugetApiKey: ${{ secrets.NUGET_API_KEY }}
