name: Publish Allegro.Extensions.ApplicationInsights

on:
  workflow_dispatch: {}
  push:
    tags:
      - 'Allegro.Extensions.ApplicationInsights_*'

jobs:
  publish1:
    uses: ./.github/workflows/template.yml
    with:
      projectName: Allegro.Extensions.ApplicationInsights.AspNetCore
      solutionName: Allegro.Extensions.ApplicationInsights
      publish: true
      tagName: ${{ github.ref_name }}
    secrets:
      nugetCertificate: ${{ secrets.NUGET_PRIVATE_KEY_P12 }}
      nugetCertificatePassword: ${{ secrets.GPG_PRIVATE_KEY_PASSWORD }}
      nugetApiKey: ${{ secrets.NUGET_API_KEY }}
  publish2:
    uses: ./.github/workflows/template.yml
    with:
      projectName: Allegro.Extensions.ApplicationInsights.Prometheus
      solutionName: Allegro.Extensions.ApplicationInsights
      publish: true
      tagName: ${{ github.ref_name }}
    secrets:
      nugetCertificate: ${{ secrets.NUGET_PRIVATE_KEY_P12 }}
      nugetCertificatePassword: ${{ secrets.GPG_PRIVATE_KEY_PASSWORD }}
      nugetApiKey: ${{ secrets.NUGET_API_KEY }}
