on:
  workflow_call:
    inputs:
      publish:
        required: false
        type: boolean
        default: false
      projectName:
        required: true
        type: string
      solutionName:
        required: true
        type: string
      tagName:
        required: false
        type: string
    secrets:
      nugetCertificate:
        required: false
      nugetCertificatePassword:
        required: false
      nugetApiKey:
        required: false
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/${{ inputs.solutionName }}
    outputs:
      nupkgFilename: ${{ steps.nupkg.outputs.filename }}
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: FormatCheck
      run: dotnet format --verify-no-changes
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Test
      run: dotnet test -c Release --no-build --verbosity normal
    - name: Pack
      run: dotnet pack -v normal -c Release --no-build --include-symbols --include-source -o package
    - name: Verify package name & version
      id: nupkg
      if: inputs.publish
      run: |
        TAG_NAME=${{ inputs.tagName }}
        VERSION=${TAG_NAME##*_}
        NUPKG="${{ inputs.projectName }}.${VERSION}.nupkg"
        echo "::set-output name=filename::$NUPKG"
        if [ ! -f package/$NUPKG ]; then
          echo "File '$NUPKG' does not exist";
          exit 1;
        fi
    - uses: actions/upload-artifact@v3
      if: inputs.publish
      with:
        name: package
        path: src/${{ inputs.solutionName }}/package
  publish:
    runs-on: windows-latest
    if: inputs.publish
    needs: [build]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: package
          path: unsigned
      - name: NuGet Install
        uses: NuGet/setup-nuget@v1.0.5
        with:
          nuget-version: latest
      - name: Setup Certificate
        run: |
          echo "${{ secrets.SM_CLIENT_CERT_FILE_B64 }}" | base64 --decode > /d/cognite_code_signing_github_actions.p12
        shell: bash
      - name: Set variables
        id: variables
        run: |
          echo "SM_HOST=${{ secrets.SM_HOST }}" >> "$GITHUB_ENV" 
          echo "SM_API_KEY=${{ secrets.SM_API_KEY }}" >> "$GITHUB_ENV" 
          echo "SM_CLIENT_CERT_PASSWORD=${{ secrets.SM_CLIENT_CERT_PASSWORD }}" >> "$GITHUB_ENV" 
          echo "SM_CODE_SIGNING_CERT_SHA1_HASH=${{ secrets.SM_CODE_SIGNING_CERT_SHA1_HASH }}" >> "$GITHUB_ENV"
          echo "SM_CLIENT_CERT_FILE=D:\\cognite_code_signing_github_actions.p12" >> "$GITHUB_ENV"
        shell: bash
      - name: Configure Digicert Secure Software Manager
        uses: digicert/ssm-code-signing@v0.0.2
        env:
          SM_API_KEY: ${{ env.SM_API_KEY }}
          SM_CLIENT_CERT_PASSWORD: ${{ env.SM_CLIENT_CERT_PASSWORD }}
          SM_CLIENT_CERT_FILE: ${{ env.SM_CLIENT_CERT_FILE }}
      - name: Setup SSM KSP on windows latest 
        run: | 
          smksp_registrar.exe list 
          smctl.exe keypair ls 
          C:\Windows\System32\certutil.exe -csp "DigiCert Signing Manager KSP" -key -user 
          smksp_cert_sync.exe 
          smctl.exe healthcheck
        shell: cmd 
      - name: Signing using Nuget
        run: |
          dir "%cd%\unsigned"
          mkdir "%cd%\signed"
          nuget sign "%cd%\unsigned\*.nupkg" -Timestamper http://timestamp.digicert.com -outputdirectory "%cd%\signed" -CertificateFingerprint ${{ secrets.SM_CODE_SIGNING_CERT_SHA1_HASH }} -HashAlgorithm SHA256 -Verbosity detailed -Overwrite
          nuget verify -All "%cd%\signed\*.nupkg"
        shell: cmd
      - name: Push package
        run: dotnet nuget push signed/*.nupkg --api-key ${{ secrets.nugetApiKey }} --skip-duplicate --source https://api.nuget.org/v3/index.json
