name: Template test

on:
  workflow_dispatch:
  pull_request:
    paths: ['.github/workflows/*']

permissions:
  actions: read
  contents: read

jobs:
  publish:
    uses: ./.github/workflows/template.yml
    with:
      projectName: Allegro.Extensions.DependencyCall
      solutionName: Allegro.Extensions.DependencyCall
      publish: true
      tagName: Allegro.Extensions.DependencyCall_1.2.0
      onPublishNugetPush: false
    secrets:
      SM_CLIENT_CERT_PASSWORD: ${{ secrets.DIGICERT_SM_CLIENT_CERT_PASSWORD }}
      SM_CLIENT_CERT_FILE_B64: ${{ secrets.DIGICERT_SM_CLIENT_CERT_FILE_B64 }}
      SM_HOST: ${{ secrets.DIGICERT_SM_HOST }}
      SM_API_KEY: ${{ secrets.DIGICERT_SM_API_KEY }}
      SM_CODE_SIGNING_CERT_SHA1_HASH: ${{ secrets.DIGICERT_SM_CODE_SIGNING_CERT_SHA1_HASH }}
      nugetApiKey: ${{ secrets.NUGET_API_KEY }}
